# Generated by Django 6.0.1 on 2026-01-24 06:04

import app_depts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creditor_type', models.CharField(choices=[('BANK', 'Банк'), ('MFO', 'МФО'), ('PERSON', 'Частное лицо'), ('OTHER', 'Прочее')], default='BANK', max_length=10, verbose_name='Тип')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Формат: +79991234567')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Кредитор',
                'verbose_name_plural': 'Кредиторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'СРО',
                'verbose_name_plural': 'СРО',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('loan_type', models.CharField(choices=[('PAYDAY', 'Займ до зарплаты'), ('CONSUMER', 'Потребительский кредит'), ('MORTGAGE', 'Ипотека'), ('CARD', 'Кредитная карта'), ('AUTO', 'Автокредит'), ('LINE', 'Кредитная линия')], default='CONSUMER', max_length=15, verbose_name='Тип')),
                ('start_date', models.DateField(validators=[app_depts.models.validate_not_future], verbose_name='Дата открытия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Плановое закрытие')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Закрыт')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='app_depts.creditor', verbose_name='Кредитор')),
            ],
            options={
                'verbose_name': 'Запись долга',
                'verbose_name_plural': 'Записи долгов',
                'unique_together': {('name', 'creditor')},
            },
        ),
        migrations.AddField(
            model_name='creditor',
            name='sro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditors', to='app_depts.sro', verbose_name='СРО'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACCRUAL', 'Начисление (тело долга)'), ('PAYMENT', 'Оплата'), ('INTEREST', 'Проценты'), ('PENALTY', 'Штраф/Пени'), ('WRITE_OFF', 'Списание'), ('COLLECTION', 'Передача коллекторам'), ('CORRECTION', 'Корректировка')], max_length=20, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[app_depts.models.validate_not_future], verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_depts.record', verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
