# Generated by Django 6.0.1 on 2026-01-23 11:50

import app_depts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('website', models.URLField(blank=True, default='https://www.', max_length=100, unique=True, validators=[app_depts.models.validate_website_domain], verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: 8-000-00-00', regex='^8-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'СРО',
                'verbose_name_plural': 'СРО',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('website', models.URLField(blank=True, default='https://www.', max_length=100, unique=True, validators=[app_depts.models.validate_website_domain], verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: 8-000-00-00', regex='^8-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('sro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditors', to='app_depts.sro', verbose_name='Связь с СРО')),
            ],
            options={
                'verbose_name': 'Кредитор',
                'verbose_name_plural': 'Кредиторы',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма долга')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Выплаченная сумма')),
                ('start_date', models.DateField(verbose_name='Дата кредита')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания кредита')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Долг оплачен')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='app_depts.creditor', verbose_name='Кредитор')),
            ],
            options={
                'verbose_name': 'Запись долга',
                'verbose_name_plural': 'Записи долгов',
                'ordering': ['-start_date'],
                'abstract': False,
                'unique_together': {('name', 'creditor')},
            },
        ),
    ]
