# Generated by Django 6.0.1 on 2026-01-23 14:07

import app_depts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_depts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: 8-000-00-00', regex='^8-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='website',
            field=models.URLField(blank=True, default='https://www.', max_length=100, null=True, unique=True, validators=[app_depts.models.validate_website_domain], verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: 8-000-00-00', regex='^8-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='website',
            field=models.URLField(blank=True, default='https://www.', max_length=100, null=True, unique=True, validators=[app_depts.models.validate_website_domain], verbose_name='Сайт'),
        ),
    ]
