# Generated by Django 6.0.1 on 2026-01-24 10:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_depts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AddConstraint(
            model_name='creditor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_creditor_name_case_insensitive'),
        ),
    ]
