# Generated by Django 6.0.1 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_depts', '0002_alter_creditor_phone_alter_creditor_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7 (999) 000-00-00', max_length=13, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7 (999) 000-00-00', max_length=13, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
