# Generated by Django 6.0.1 on 2026-01-25 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_depts', '0002_alter_creditor_name_alter_sro_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditor',
            name='unique_creditor_name_case_insensitive',
        ),
        migrations.AddField(
            model_name='creditor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='sro',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Формат: +79991234567')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='sro',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='sro',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
