# Generated by Django 6.0.1 on 2026-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_depts', '0003_remove_creditor_unique_creditor_name_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='loan_type',
            field=models.CharField(choices=[('PAY', 'Взаймы'), ('PAYDAY', 'Займ до зарплаты'), ('CONSUMER', 'Потребительский кредит'), ('MORTGAGE', 'Ипотека'), ('CARD', 'Кредитная карта'), ('AUTO', 'Автокредит'), ('LINE', 'Кредитная линия')], default='CONSUMER', max_length=15, verbose_name='Тип'),
        ),
    ]
