# Generated by Django 6.0.1 on 2026-02-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_depts', '0004_alter_record_loan_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
    ]
