# Generated by Django 6.0.1 on 2026-01-30 06:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название сезона')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий сезон')),
                ('start_date', models.DateField(verbose_name='Дата начала (включительно)')),
                ('end_date', models.DateField(verbose_name='Дата окончания (включительно)')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('football', 'Футбол'), ('hockey', 'Хоккей'), ('tennis', 'Теннис'), ('volleyball', 'Волейбол'), ('basketball', 'Баскетбол')], max_length=20, unique=True, verbose_name='Вид спорта')),
                ('has_draw', models.BooleanField(default=True, help_text="Определяет, принимает ли букмекер ставки на 'Х' в основное время.", verbose_name='Ничья в линии')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название лиги')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_leagues', to='app_bets.country')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_leagues', to='app_bets.sport')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
                'unique_together': {('name', 'sport', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Каноническое название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bets.country')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bets.sport')),
            ],
            options={
                'verbose_name': 'Команда / Игрок',
                'verbose_name_plural': 'Команды и Игроки',
                'unique_together': {('name', 'sport', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('round_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тур')),
                ('home_score_reg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Осн. время (Дома)')),
                ('away_score_reg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Осн. время (Гости)')),
                ('home_score_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговый (Дома)')),
                ('away_score_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговый (Гости)')),
                ('finish_type', models.CharField(choices=[('REG', 'Основное время'), ('OT', 'Овертайм'), ('SO', 'Буллиты/Пенальти')], default='REG', max_length=3, verbose_name='Завершение игры')),
                ('odds_home', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф П1')),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф Х')),
                ('odds_away', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф П2')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Аномальный результат')),
                ('home_lineup', models.JSONField(blank=True, null=True, verbose_name='Состав (Дома)')),
                ('away_lineup', models.JSONField(blank=True, null=True, verbose_name='Состав (Гости)')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_bets.league')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_bets.season', verbose_name='Сезон')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='app_bets.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='app_bets.team')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Вариант из источника')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='app_bets.team')),
            ],
        ),
    ]
