# Generated by Django 6.0.1 on 2026-01-31 10:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
        migrations.AlterModelOptions(
            name='teamalias',
            options={'verbose_name': 'Псевдоним команды', 'verbose_name_plural': 'Псевдонимы команд'},
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_leagues', to='app_bets.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_leagues', to='app_bets.sport', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_away',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф П2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_draw',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф Х'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_home',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф П1'),
        ),
    ]
