# Generated by Django 6.0.1 on 2026-02-02 11:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bets', '0002_alter_sport_options_alter_teamalias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='odds_away',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф П2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_draw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф Х'),
        ),
        migrations.AlterField(
            model_name='match',
            name='odds_home',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Кэф П1'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='app_bets_co_name_35c10e_idx'),
        ),
        migrations.AddIndex(
            model_name='league',
            index=models.Index(fields=['name'], name='app_bets_le_name_c86521_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['odds_home', 'odds_away'], name='app_bets_ma_odds_ho_132047_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['name'], name='app_bets_se_name_05b849_idx'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['name'], name='app_bets_sp_name_26f321_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='app_bets_te_name_342868_idx'),
        ),
        migrations.AddIndex(
            model_name='teamalias',
            index=models.Index(fields=['name'], name='app_bets_te_name_7d14ff_idx'),
        ),
    ]
