# Generated by Django 6.0.1 on 2026-02-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bets', '0003_alter_match_odds_away_alter_match_odds_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='external_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Внешний код (например, E0)'),
        ),
    ]
